// DictusKeyboard/Models/EmojiSearchFR.swift
import Foundation

/// French keyword → emoji reverse index for localized emoji search.
///
/// WHY a reverse index instead of per-emoji keywords:
/// A reverse index (keyword → [emojis]) is more compact than per-emoji mappings
/// because many emojis share keywords. ~200 keyword groups cover the most common
/// French search terms while keeping memory usage low (~15KB).
///
/// Search logic: if the user's query is a substring of any keyword, all emojis
/// mapped to that keyword are returned. Example: "feu" matches keywords "feu",
/// "feux", returning 🔥🧯🚒 etc.
enum EmojiSearchFR {
    /// Reverse index: French keyword → emojis that match.
    /// Keywords are lowercased, accented (é, è, ê, etc.) for proper matching.
    static let keywords: [String: [String]] = [
        // MARK: - Emotions & expressions
        "sourire": ["😀", "😃", "😄", "😁", "😊", "🙂", "☺️", "😺"],
        "rire": ["😂", "🤣", "😆", "😅", "😹"],
        "clin d'oeil": ["😉", "😜"],
        "bisou": ["😘", "😗", "😚", "😙", "😽", "💋", "💏"],
        "amour": ["🥰", "😍", "😘", "❤️", "💕", "💗", "💖", "💘", "💝", "💞", "💓", "💟", "❣️", "💑", "🥰"],
        "coeur": ["❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "❤️‍🔥", "❤️‍🩹", "💔", "💕", "💞", "💓", "💗", "💖", "💘", "💝", "💟", "❣️", "♥️"],
        "triste": ["😢", "😭", "😞", "😔", "🙁", "☹️", "😿", "💔"],
        "pleurer": ["😢", "😭", "😿", "🥲"],
        "colère": ["😡", "😠", "🤬", "😤", "💢"],
        "peur": ["😨", "😰", "😱", "😧", "😦", "🫣"],
        "surprise": ["😮", "😯", "😲", "😳", "🤯", "😱"],
        "malade": ["🤒", "🤕", "🤢", "🤮", "😷", "🥴", "🤧"],
        "dormir": ["😴", "😪", "🛌", "💤", "🛏️"],
        "cool": ["😎", "🤩", "🆒"],
        "diable": ["😈", "👿", "👹", "👺"],
        "fantôme": ["👻"],
        "crâne": ["💀", "☠️", "🦴"],
        "robot": ["🤖"],
        "alien": ["👽", "👾", "🛸"],
        "clown": ["🤡"],
        "caca": ["💩"],
        "singe": ["🐵", "🐒", "🙈", "🙉", "🙊"],
        "pensif": ["🤔", "🧐", "💭"],
        "secret": ["🤫", "🤐"],
        "honte": ["😳", "😶", "🫢"],
        "fête": ["🥳", "🎉", "🎊", "🎈", "🎀", "🎆", "🎇", "🪅"],
        "ok": ["👌", "🤌", "👍", "✅", "🆗"],
        "bravo": ["👏", "🙌", "🎉", "👍"],
        "merci": ["🙏", "🤝", "💐"],

        // MARK: - Gestes & corps
        "main": ["👋", "🤚", "🖐️", "✋", "🖖", "🫱", "🫲", "🫳", "🫴", "👐", "🤲"],
        "pouce": ["👍", "👎"],
        "doigt": ["👈", "👉", "👆", "👇", "☝️", "🫵", "🖕"],
        "poing": ["✊", "👊", "🤛", "🤜"],
        "victoire": ["✌️", "🏆", "🥇"],
        "muscle": ["💪", "🦾"],
        "oeil": ["👀", "👁️", "🧿"],
        "yeux": ["👀", "👁️", "🥺", "🥹"],
        "bouche": ["👄", "👅", "🫦"],
        "nez": ["👃"],
        "oreille": ["👂", "🦻"],
        "cerveau": ["🧠"],
        "os": ["🦴", "💀", "☠️"],

        // MARK: - Personnes
        "bébé": ["👶", "🍼", "👼"],
        "enfant": ["🧒", "👦", "👧"],
        "homme": ["👨", "🧔", "👴", "🧓", "🤵", "👷"],
        "femme": ["👩", "👵", "🧓", "👰", "👸"],
        "famille": ["👪", "👨‍👩‍👦", "👨‍👩‍👧", "👨‍👩‍👧‍👦", "👨‍👩‍👦‍👦", "👨‍👩‍👧‍👧"],
        "roi": ["🤴", "👑"],
        "reine": ["👸", "👑"],
        "prince": ["🤴"],
        "princesse": ["👸"],
        "père noël": ["🎅", "🤶"],
        "ninja": ["🥷"],
        "police": ["👮", "🚔", "🚨"],
        "pompier": ["🧑‍🚒", "🚒", "🧯"],
        "docteur": ["👨‍⚕️", "👩‍⚕️", "🩺", "💊", "💉"],
        "danse": ["💃", "🕺", "🩰"],
        "yoga": ["🧘"],

        // MARK: - Animaux
        "chat": ["🐱", "🐈", "🐈‍⬛", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", "😿", "😾"],
        "chien": ["🐶", "🐕", "🐩", "🦮", "🐕‍🦺"],
        "cheval": ["🐴", "🐎", "🏇", "🦄"],
        "licorne": ["🦄"],
        "oiseau": ["🐦", "🐤", "🐣", "🐥", "🦆", "🦅", "🦉", "🕊️", "🦜", "🦢", "🦩", "🪿"],
        "poisson": ["🐟", "🐠", "🐡", "🎣", "🐬", "🐳", "🐋", "🦈"],
        "papillon": ["🦋"],
        "abeille": ["🐝"],
        "coccinelle": ["🐞"],
        "serpent": ["🐍"],
        "tortue": ["🐢"],
        "grenouille": ["🐸"],
        "souris": ["🐭", "🐁"],
        "lapin": ["🐰", "🐇"],
        "ours": ["🐻", "🐼", "🐻‍❄️"],
        "panda": ["🐼"],
        "lion": ["🦁"],
        "tigre": ["🐯", "🐅"],
        "cochon": ["🐷", "🐽", "🐖", "🐗"],
        "vache": ["🐮", "🐄", "🐂", "🐃"],
        "mouton": ["🐑", "🐏"],
        "poule": ["🐔", "🐓"],
        "pingouin": ["🐧"],
        "renard": ["🦊"],
        "loup": ["🐺"],
        "dinosaure": ["🦖", "🦕"],
        "dragon": ["🐉", "🐲"],
        "requin": ["🦈"],
        "baleine": ["🐳", "🐋"],
        "dauphin": ["🐬"],
        "pieuvre": ["🐙"],
        "crabe": ["🦀"],
        "crevette": ["🦐"],
        "escargot": ["🐌"],
        "araignée": ["🕷️", "🕸️"],
        "éléphant": ["🐘"],
        "girafe": ["🦒"],
        "crocodile": ["🐊"],

        // MARK: - Nature & météo
        "soleil": ["☀️", "🌞", "🌅", "🌄", "🌤️", "⛅"],
        "lune": ["🌙", "🌛", "🌜", "🌝", "🌚", "🌕", "🌖", "🌗", "🌘", "🌑", "🌒", "🌓", "🌔"],
        "étoile": ["⭐", "🌟", "✨", "💫", "🌠"],
        "nuage": ["☁️", "🌥️", "⛅", "🌦️", "🌧️", "🌨️", "🌩️"],
        "pluie": ["🌧️", "🌦️", "⛈️", "☔", "☂️", "💧"],
        "neige": ["❄️", "☃️", "⛄", "🌨️"],
        "orage": ["⛈️", "🌩️", "⚡"],
        "éclair": ["⚡", "🌩️"],
        "arc-en-ciel": ["🌈"],
        "vent": ["🌬️", "💨", "🌪️"],
        "tornade": ["🌪️"],
        "feu": ["🔥", "❤️‍🔥", "🧯", "🧨", "🎆"],
        "flamme": ["🔥", "❤️‍🔥"],
        "eau": ["💧", "💦", "🌊", "🚰"],
        "vague": ["🌊"],
        "fleur": ["🌸", "🌹", "🌻", "🌼", "🌷", "🌺", "💐", "🥀", "🌿", "☘️", "🍀"],
        "rose": ["🌹", "🥀"],
        "arbre": ["🌲", "🌳", "🌴", "🎄", "🪵"],
        "feuille": ["🍃", "🍂", "🍁", "🌿", "☘️", "🍀"],
        "champignon": ["🍄"],
        "cactus": ["🌵"],
        "terre": ["🌍", "🌎", "🌏", "🗺️"],
        "planète": ["🌍", "🌎", "🌏", "🪐"],
        "volcan": ["🌋"],
        "montagne": ["⛰️", "🏔️", "🗻"],

        // MARK: - Nourriture & boissons
        "pomme": ["🍎", "🍏"],
        "banane": ["🍌"],
        "raisin": ["🍇"],
        "fraise": ["🍓"],
        "cerise": ["🍒"],
        "pêche": ["🍑"],
        "citron": ["🍋"],
        "orange": ["🍊"],
        "pastèque": ["🍉"],
        "ananas": ["🍍"],
        "mangue": ["🥭"],
        "avocat": ["🥑"],
        "tomate": ["🍅"],
        "carotte": ["🥕"],
        "maïs": ["🌽"],
        "brocoli": ["🥦"],
        "salade": ["🥗", "🥬"],
        "pain": ["🍞", "🥖", "🥐", "🥯", "🫓"],
        "baguette": ["🥖"],
        "croissant": ["🥐"],
        "fromage": ["🧀"],
        "oeuf": ["🥚", "🍳"],
        "viande": ["🍖", "🍗", "🥩", "🥓"],
        "poulet": ["🍗", "🐔"],
        "hamburger": ["🍔"],
        "burger": ["🍔"],
        "pizza": ["🍕"],
        "frites": ["🍟"],
        "hot-dog": ["🌭"],
        "sandwich": ["🥪"],
        "taco": ["🌮"],
        "sushi": ["🍣", "🍱"],
        "pâtes": ["🍝"],
        "riz": ["🍚", "🍛", "🍙"],
        "soupe": ["🍲", "🥣"],
        "gâteau": ["🎂", "🍰", "🧁"],
        "glace": ["🍦", "🍧", "🍨"],
        "chocolat": ["🍫"],
        "bonbon": ["🍬", "🍭"],
        "biscuit": ["🍪"],
        "donut": ["🍩"],
        "miel": ["🍯"],
        "café": ["☕", "🫖"],
        "thé": ["🍵", "🫖"],
        "bière": ["🍺", "🍻"],
        "vin": ["🍷", "🍾"],
        "cocktail": ["🍸", "🍹"],
        "champagne": ["🍾", "🥂"],
        "jus": ["🧃", "🥤"],
        "lait": ["🥛", "🍼"],
        "biberon": ["🍼"],

        // MARK: - Transport & voyage
        "voiture": ["🚗", "🚕", "🚙", "🏎️", "🚓", "🚘"],
        "taxi": ["🚕"],
        "bus": ["🚌", "🚎", "🚍"],
        "camion": ["🚚", "🚛"],
        "moto": ["🏍️", "🛵"],
        "vélo": ["🚲", "🚴", "🚵"],
        "train": ["🚂", "🚃", "🚄", "🚅", "🚆", "🚇", "🚈", "🚉", "🚊", "🚝", "🚞"],
        "avion": ["✈️", "🛫", "🛬", "🛩️"],
        "fusée": ["🚀"],
        "bateau": ["⛵", "🚤", "🛥️", "🛳️", "⛴️", "🚢", "🛶"],
        "hélicoptère": ["🚁"],
        "ambulance": ["🚑"],
        "maison": ["🏠", "🏡", "🏘️"],
        "château": ["🏰", "🏯"],
        "église": ["⛪"],
        "hôpital": ["🏥"],
        "école": ["🏫"],
        "hôtel": ["🏨"],
        "plage": ["🏖️", "⛱️", "🌊"],
        "île": ["🏝️"],
        "camping": ["🏕️", "⛺"],
        "statue": ["🗽", "🗿"],
        "drapeau": ["🏳️", "🏴", "🚩", "🎌", "🏳️‍🌈"],
        "france": ["🇫🇷"],

        // MARK: - Objets
        "téléphone": ["📱", "📲", "📞", "☎️"],
        "ordinateur": ["💻", "🖥️", "⌨️"],
        "montre": ["⌚", "🕰️"],
        "appareil photo": ["📷", "📸"],
        "caméra": ["📹", "🎥", "📽️"],
        "télévision": ["📺"],
        "radio": ["📻"],
        "lampe": ["💡", "🔦"],
        "bougie": ["🕯️"],
        "argent": ["💰", "💵", "💴", "💶", "💷", "🪙", "💸", "💳"],
        "diamant": ["💎"],
        "clé": ["🔑", "🗝️"],
        "cadenas": ["🔒", "🔓", "🔐"],
        "porte": ["🚪"],
        "chaise": ["🪑"],
        "lit": ["🛏️", "🛌"],
        "toilettes": ["🚽"],
        "douche": ["🚿"],
        "baignoire": ["🛁"],
        "ciseaux": ["✂️"],
        "stylo": ["🖊️", "🖋️", "✒️", "✏️"],
        "crayon": ["✏️", "🖍️"],
        "livre": ["📖", "📚", "📕", "📗", "📘", "📙"],
        "lettre": ["✉️", "📩", "📨", "📧", "💌"],
        "cadeau": ["🎁", "🎀"],
        "ballon": ["🎈"],
        "médicament": ["💊", "💉"],
        "seringue": ["💉"],
        "thermomètre": ["🌡️"],
        "loupe": ["🔍", "🔎"],
        "bombe": ["💣", "🧨"],
        "couteau": ["🔪", "🗡️"],
        "bouclier": ["🛡️"],
        "épée": ["⚔️", "🗡️"],

        // MARK: - Activités & sport
        "football": ["⚽"],
        "foot": ["⚽"],
        "basket": ["🏀"],
        "tennis": ["🎾"],
        "rugby": ["🏉"],
        "golf": ["⛳", "🏌️"],
        "ski": ["⛷️", "🎿"],
        "surf": ["🏄"],
        "natation": ["🏊", "🤽"],
        "boxe": ["🥊"],
        "judo": ["🥋"],
        "trophée": ["🏆"],
        "médaille": ["🥇", "🥈", "🥉", "🏅", "🎖️"],
        "musique": ["🎵", "🎶", "🎼", "🎤", "🎧", "🎹", "🎸", "🎷", "🎺", "🥁", "🎻"],
        "guitare": ["🎸"],
        "piano": ["🎹"],
        "micro": ["🎤", "🎙️"],
        "jeu": ["🎮", "🕹️", "🎲", "🎯", "🧩", "♟️"],
        "manette": ["🎮", "🕹️"],
        "cinéma": ["🎬", "🎥", "🍿"],
        "film": ["🎬", "🎞️", "🎥"],
        "art": ["🎨", "🖌️", "🖼️"],
        "peinture": ["🎨", "🖌️"],
        "théâtre": ["🎭"],
        "cirque": ["🎪", "🤹"],
        "feux d'artifice": ["🎆", "🎇", "🧨"],

        // MARK: - Symboles
        "interdit": ["🚫", "⛔", "❌"],
        "attention": ["⚠️", "❗", "❕"],
        "question": ["❓", "❔", "⁉️"],
        "exclamation": ["❗", "❕", "‼️"],
        "check": ["✅", "✔️", "☑️"],
        "croix": ["❌", "❎", "✖️"],
        "plus": ["➕"],
        "moins": ["➖"],
        "flèche": ["➡️", "⬅️", "⬆️", "⬇️", "↗️", "↘️", "↙️", "↖️", "↕️", "↔️"],
        "recycler": ["♻️"],
        "infini": ["♾️"],
        "dollar": ["💲", "💵"],
        "euro": ["💶", "€"],
        "horloge": ["🕐", "🕑", "🕒", "🕓", "🕔", "🕕", "🕖", "🕗", "🕘", "🕙", "🕚", "🕛", "⏰", "⏱️", "⏲️"],
        "temps": ["⏰", "⏱️", "⏲️", "🕰️", "⌛", "⏳"],
        "paix": ["☮️", "🕊️"],
        "étoile filante": ["🌠", "💫"],
        "chance": ["🍀", "🎰", "🤞"],
        "cent": ["💯"],
        "sos": ["🆘"],
        "nouveau": ["🆕"],
        "gratuit": ["🆓"],

        // MARK: - Drapeaux courants
        "français": ["🇫🇷"],
        "américain": ["🇺🇸"],
        "anglais": ["🇬🇧"],
        "allemand": ["🇩🇪"],
        "espagnol": ["🇪🇸"],
        "italien": ["🇮🇹"],
        "japonais": ["🇯🇵"],
        "canadien": ["🇨🇦"],
        "belge": ["🇧🇪"],
        "suisse": ["🇨🇭"],
        "marocain": ["🇲🇦"],
        "algérien": ["🇩🇿"],
        "tunisien": ["🇹🇳"],
        "brésilien": ["🇧🇷"],
        "portugais": ["🇵🇹"],
        "ukrainien": ["🇺🇦"],

        // MARK: - Expressions courantes
        "merveilleux": ["🤩", "✨", "💫"],
        "super": ["🦸", "🦹", "💪", "👍", "🔥"],
        "nul": ["👎", "💩", "😒"],
        "fatigué": ["😩", "😫", "🥱", "😴"],
        "affamé": ["🤤", "😋", "🍽️"],
        "chaud": ["🥵", "🔥", "☀️", "🌡️"],
        "froid": ["🥶", "❄️", "⛄", "🌨️"],
        "anniversaire": ["🎂", "🎈", "🎉", "🎊", "🎁", "🥳"],
        "noël": ["🎄", "🎅", "🤶", "🎁", "❄️", "⛄"],
        "halloween": ["🎃", "👻", "🦇", "🕷️", "🕸️", "💀"],
        "vacances": ["🏖️", "✈️", "🌴", "🏝️", "🧳", "🌊"],
        "travail": ["💼", "🏢", "💻", "📊", "📈"],
        "étude": ["📚", "📖", "✏️", "🎓", "🏫"],
        "météo": ["☀️", "🌧️", "⛅", "🌈", "❄️", "⚡"],
        "nuit": ["🌙", "🌛", "🌜", "🌃", "🌌", "⭐"],
        "matin": ["🌅", "☀️", "🌄"],
        "soir": ["🌇", "🌆", "🌃"],
    ]
}
